error: this function marked with `#[test]` cannot fail and will always succeed
  --> tests/ui/test_without_fail_case.rs:23:1
   |
LL | / fn test_without_fail() {
LL | |     let x = 5;
LL | |     let y = x + 2;
LL | |     println!("y: {}", y);
LL | | }
   | |_^
   |
   = note: consider adding assertions or panics to test failure cases
   = note: `-D clippy::test-without-fail-case` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::test_without_fail_case)]`

error: this function marked with `#[test]` cannot fail and will always succeed
  --> tests/ui/test_without_fail_case.rs:78:1
   |
LL | / fn test_slice_index() {
LL | |     let a = [1, 2, 3, 4, 5, 6];
LL | |     // indexing into slice, this can fail but by default check for this is disabled.
LL | |     let b = a[0];
LL | | }
   | |_^
   |
   = note: consider adding assertions or panics to test failure cases

error: aborting due to 2 previous errors

